import java.io.Serializable;

/*
 * Student name: Haoze Xia
 * Student ID: 1131343
 * LMS username: haozex
 */

public class Entry implements Serializable {
    /**
	 * This class is use to record all entry Info
	 * each competition can have multiple Entry
	 * and each entry can be NumbersEntry or
	 * AutoNumbersEntry 
	 */
	private static final long serialVersionUID = 1L;  //serializable ID
	private int entryId;  //entry Id  
    private String billId;  //bill Id
    private String memberId;  //member Id
    private int prize;  // prize for each entry
    private boolean manualType; //determine is manual or not 
    
    /**
     * This is a empty constructor for Entry class
     * */
    public Entry() {
    	
    }
    
    /**
     * This is a constructor for Entry Class
     * @param entryId is the entry ID
     * @param billId is the Bill ID
     * @param memberId is the member ID
     * @param manualType is to determine is generated by manual or not
     * */
    public Entry(int entryId, String billId, String memberId, boolean manualType) {
    	this.entryId = entryId;
    	this.billId = billId;
    	this.memberId =memberId;
    	this.manualType =manualType;
    }
    
    /**
     * This is a constructor for Entry Class
     * @param entryId is the entry ID
     * @param billId is the Bill ID
     * @param memberId is the member ID
     * */
    public Entry(int entryId, String billId, String memberId) {
    	this.entryId = entryId;
    	this.billId = billId;
    	this.memberId =memberId;
    }
    
	/**
	 * @return the entryId
	 */
	public int getEntryId() {
		return entryId;
	}
	
	/**
	 * @return the billId
	 */
	public String getBillId() {
		return billId;
	}
	
	/**
	 * @return the memberId
	 */
	public String getMemberId() {
		return memberId;
	}
	
	/**
	 * @return the prize
	 */
	public int getPrize() {
		return prize;
	}
	
	/**
	 * @param prize the prize to set
	 */
	public void setPrize(int prize) {
		this.prize = prize;
	}
	
	/**
	 * @return the manualType
	 */
	public boolean isManualType() {
		return manualType;
	}
    
}
